language: node_js
node_js:
- '5'
- '4'
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_9a2810c1eadf_key -iv $encrypted_9a2810c1eadf_iv -in ./.ci/deploy-key.enc -out ./.ci/deploy-key -d
after_success:
- eval "$(ssh-agent)"
- chmod 600 ./.ci/deploy-key
- ssh-add ./.ci/deploy-key
- if [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then echo "Publishing Docs" && npm run publish-docs; fi;
